---

:project:
  :use_exceptions: false
  :use_test_preprocessor: true
  :use_deep_dependencies: true
  :build_root: build
  :test_file_prefix: test_
  :options_paths:
    - config/

:release_build:
  :output: kinetic-c

# Enable this section to configure environment vars, if needed
# :environment:

:paths:
  :test:
    - +:test/**
    - -:test/support
    - -:test/system
  :support:
    - test/support/**
  :source:
    - src/lib/**
    - src/utility/**
  :include:
    - src/**
    - include/**
    - "#{ENV['PROTOBUFCPATH']}/protobuf-c/**"
    - "#{ENV['KINETICPROTOPATH']}/kinetic/**"
    - "#{ENV['SOCKET99PATH']}/socket99.h"
:defines:
  :commmon: &common_defines
    - TEST
  :test:
    - *common_defines
  :test_preprocess:
    - *common_defines

:flags:
  :test:
    :link:
      :test_kinetic_hmac:
        - -l libssl

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :error
  :enforce_strict_ordering: true
  :plugins:
    - :ignore
    - :return_thru_ptr
  :unity_helper_path: test/support/unity_helper.h
  :includes_h_post_orig_header:
    - "unity.h"
    - "unity_helper.h"
  :treat_as:
    uint8_t:    HEX8
    uint16_t:   HEX16
    uint32_t:   UINT32
    int8_t:     INT8
    bool_t:     BOOL
    size_t:     INT
  :callback_include_count: true

:tools:
  :test_includes_preprocessor:
    :executable: "#{ENV.fetch('CC', 'gcc')}"
    :arguments:
      - -E
      - -MM
      - -MG
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D"$": COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D"$": DEFINES_TEST_PREPROCESS
      - -DGNU_COMPILER
      - -D_POSIX_C_SOURCE=199309L
      - -D_C99_SOURCE=1
      - -std=c99
      - -g
      - -Wall
      - -Wextra
      - -Werror
      - -pedantic
      - -Wstrict-prototypes
      - -Werror=implicit-function-declaration
      - ${1}
  :test_compiler:
    :executable: "#{ENV.fetch('CC', 'gcc')}"
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D"$": COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGNU_COMPILER
      - -D_POSIX_C_SOURCE=199309L
      - -D_C99_SOURCE=1
      - -std=c99
      - -g
      - -Wall
      - -Wextra
      - -Wno-pragmas
      - -Wstrict-prototypes
      - -Werror=implicit-function-declaration
      - -Wno-nonnull
      - -Wno-address
      - -Wno-missing-field-initializers
      - -c ${1}
      - -o ${2}
  :test_linker:
    :executable: "#{ENV.fetch('CC', 'gcc')}"
    :name: test_linker
    :arguments:
      - "\"${1}\""
      - -l crypto
      - "-o \"${2}\""
      - -l pthread
      - -l json-c
      - -l kinetic.pb-c
      - -l protobuf-c
      - -l socket99

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_ide_tests_report
...
