#!/bin/sh
##################################################
# Construct a flame graph for a specific command.
# Linux-specific, and requires the "perf" package.
##################################################

CMD="$2"

if [ -z "$1" ]; then
    echo "Usage: mk_flamegraph  FLAMEGRAPH_PATH  COMMAND"
    echo -n "Download flamegraph from https://github.com/brendangregg/FlameGraph.git and"
    echo " provide path to flamegraph.pl as FLAMEGRAPH_PATH"
else
    pwd
    # -g: call graph
    sudo perf record --freq=993 --all-cpus -g --output=perf.out -- ${CMD}
    sudo perf script --input=perf.out | $1/stackcollapse-perf.pl > out.perf-folded
    $1/flamegraph.pl out.perf-folded > perf_out.svg
fi
